# Generated by Django 4.0.4 on 2022-06-02 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='upload',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
